services:
  db:
    image: mysql
    restart: always
    container_name: mysql-api-tarefas
    volumes:
      - /data/mysq-api-tarefas:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DbTarefas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"